// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/notification/proto/notification.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =================
// Enum
// =================
type ActionTypeEnum int32

const (
	ActionTypeEnum_TOP_UP_BALANCE              ActionTypeEnum = 0
	ActionTypeEnum_TRANSFER_BALANCE            ActionTypeEnum = 1
	ActionTypeEnum_RECEIVED_BALANCE            ActionTypeEnum = 2
	ActionTypeEnum_LOW_BALANCE_REMINDER        ActionTypeEnum = 3
	ActionTypeEnum_APPROVAL_APP_MANAGEMENT     ActionTypeEnum = 4
	ActionTypeEnum_APPROVAL_CUSTOMIZE_APP_PAGE ActionTypeEnum = 5
)

// Enum value maps for ActionTypeEnum.
var (
	ActionTypeEnum_name = map[int32]string{
		0: "TOP_UP_BALANCE",
		1: "TRANSFER_BALANCE",
		2: "RECEIVED_BALANCE",
		3: "LOW_BALANCE_REMINDER",
		4: "APPROVAL_APP_MANAGEMENT",
		5: "APPROVAL_CUSTOMIZE_APP_PAGE",
	}
	ActionTypeEnum_value = map[string]int32{
		"TOP_UP_BALANCE":              0,
		"TRANSFER_BALANCE":            1,
		"RECEIVED_BALANCE":            2,
		"LOW_BALANCE_REMINDER":        3,
		"APPROVAL_APP_MANAGEMENT":     4,
		"APPROVAL_CUSTOMIZE_APP_PAGE": 5,
	}
)

func (x ActionTypeEnum) Enum() *ActionTypeEnum {
	p := new(ActionTypeEnum)
	*p = x
	return p
}

func (x ActionTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_api_notification_proto_notification_proto_enumTypes[0].Descriptor()
}

func (ActionTypeEnum) Type() protoreflect.EnumType {
	return &file_api_notification_proto_notification_proto_enumTypes[0]
}

func (x ActionTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionTypeEnum.Descriptor instead.
func (ActionTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_api_notification_proto_notification_proto_rawDescGZIP(), []int{0}
}

type CaseActionType_BalanceEnum int32

const (
	CaseActionType_waiting_for_invoice                    CaseActionType_BalanceEnum = 0
	CaseActionType_invoice_issued_and_waiting_for_payment CaseActionType_BalanceEnum = 1
	CaseActionType_waiting_for_verification               CaseActionType_BalanceEnum = 2
	CaseActionType_balance_rejected                       CaseActionType_BalanceEnum = 3
	CaseActionType_approved                               CaseActionType_BalanceEnum = 4
	CaseActionType_overdue                                CaseActionType_BalanceEnum = 5
)

// Enum value maps for CaseActionType_BalanceEnum.
var (
	CaseActionType_BalanceEnum_name = map[int32]string{
		0: "waiting_for_invoice",
		1: "invoice_issued_and_waiting_for_payment",
		2: "waiting_for_verification",
		3: "balance_rejected",
		4: "approved",
		5: "overdue",
	}
	CaseActionType_BalanceEnum_value = map[string]int32{
		"waiting_for_invoice":                    0,
		"invoice_issued_and_waiting_for_payment": 1,
		"waiting_for_verification":               2,
		"balance_rejected":                       3,
		"approved":                               4,
		"overdue":                                5,
	}
)

func (x CaseActionType_BalanceEnum) Enum() *CaseActionType_BalanceEnum {
	p := new(CaseActionType_BalanceEnum)
	*p = x
	return p
}

func (x CaseActionType_BalanceEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaseActionType_BalanceEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_api_notification_proto_notification_proto_enumTypes[1].Descriptor()
}

func (CaseActionType_BalanceEnum) Type() protoreflect.EnumType {
	return &file_api_notification_proto_notification_proto_enumTypes[1]
}

func (x CaseActionType_BalanceEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaseActionType_BalanceEnum.Descriptor instead.
func (CaseActionType_BalanceEnum) EnumDescriptor() ([]byte, []int) {
	return file_api_notification_proto_notification_proto_rawDescGZIP(), []int{0, 0}
}

type CaseActionType_ApprovalEnum int32

const (
	CaseActionType_submit_approval_for_changes CaseActionType_ApprovalEnum = 0
	CaseActionType_changes_approved            CaseActionType_ApprovalEnum = 1
	CaseActionType_changes_rejected            CaseActionType_ApprovalEnum = 2
)

// Enum value maps for CaseActionType_ApprovalEnum.
var (
	CaseActionType_ApprovalEnum_name = map[int32]string{
		0: "submit_approval_for_changes",
		1: "changes_approved",
		2: "changes_rejected",
	}
	CaseActionType_ApprovalEnum_value = map[string]int32{
		"submit_approval_for_changes": 0,
		"changes_approved":            1,
		"changes_rejected":            2,
	}
)

func (x CaseActionType_ApprovalEnum) Enum() *CaseActionType_ApprovalEnum {
	p := new(CaseActionType_ApprovalEnum)
	*p = x
	return p
}

func (x CaseActionType_ApprovalEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaseActionType_ApprovalEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_api_notification_proto_notification_proto_enumTypes[2].Descriptor()
}

func (CaseActionType_ApprovalEnum) Type() protoreflect.EnumType {
	return &file_api_notification_proto_notification_proto_enumTypes[2]
}

func (x CaseActionType_ApprovalEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaseActionType_ApprovalEnum.Descriptor instead.
func (CaseActionType_ApprovalEnum) EnumDescriptor() ([]byte, []int) {
	return file_api_notification_proto_notification_proto_rawDescGZIP(), []int{0, 1}
}

type CaseActionType_PlacementStatusEnum int32

const (
	CaseActionType_submitted CaseActionType_PlacementStatusEnum = 0
	CaseActionType_completed CaseActionType_PlacementStatusEnum = 1
	CaseActionType_revoked   CaseActionType_PlacementStatusEnum = 2
	CaseActionType_rejected  CaseActionType_PlacementStatusEnum = 3
)

// Enum value maps for CaseActionType_PlacementStatusEnum.
var (
	CaseActionType_PlacementStatusEnum_name = map[int32]string{
		0: "submitted",
		1: "completed",
		2: "revoked",
		3: "rejected",
	}
	CaseActionType_PlacementStatusEnum_value = map[string]int32{
		"submitted": 0,
		"completed": 1,
		"revoked":   2,
		"rejected":  3,
	}
)

func (x CaseActionType_PlacementStatusEnum) Enum() *CaseActionType_PlacementStatusEnum {
	p := new(CaseActionType_PlacementStatusEnum)
	*p = x
	return p
}

func (x CaseActionType_PlacementStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaseActionType_PlacementStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_api_notification_proto_notification_proto_enumTypes[3].Descriptor()
}

func (CaseActionType_PlacementStatusEnum) Type() protoreflect.EnumType {
	return &file_api_notification_proto_notification_proto_enumTypes[3]
}

func (x CaseActionType_PlacementStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaseActionType_PlacementStatusEnum.Descriptor instead.
func (CaseActionType_PlacementStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_api_notification_proto_notification_proto_rawDescGZIP(), []int{0, 2}
}

type CaseActionType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to CaseAction:
	//
	//	*CaseActionType_CaseAction1
	//	*CaseActionType_CaseAction2
	//	*CaseActionType_CaseAction3
	CaseAction isCaseActionType_CaseAction `protobuf_oneof:"case_action"`
}

func (x *CaseActionType) Reset() {
	*x = CaseActionType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notification_proto_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaseActionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseActionType) ProtoMessage() {}

func (x *CaseActionType) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseActionType.ProtoReflect.Descriptor instead.
func (*CaseActionType) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (m *CaseActionType) GetCaseAction() isCaseActionType_CaseAction {
	if m != nil {
		return m.CaseAction
	}
	return nil
}

func (x *CaseActionType) GetCaseAction1() CaseActionType_BalanceEnum {
	if x, ok := x.GetCaseAction().(*CaseActionType_CaseAction1); ok {
		return x.CaseAction1
	}
	return CaseActionType_waiting_for_invoice
}

func (x *CaseActionType) GetCaseAction2() CaseActionType_ApprovalEnum {
	if x, ok := x.GetCaseAction().(*CaseActionType_CaseAction2); ok {
		return x.CaseAction2
	}
	return CaseActionType_submit_approval_for_changes
}

func (x *CaseActionType) GetCaseAction3() CaseActionType_PlacementStatusEnum {
	if x, ok := x.GetCaseAction().(*CaseActionType_CaseAction3); ok {
		return x.CaseAction3
	}
	return CaseActionType_submitted
}

type isCaseActionType_CaseAction interface {
	isCaseActionType_CaseAction()
}

type CaseActionType_CaseAction1 struct {
	CaseAction1 CaseActionType_BalanceEnum `protobuf:"varint,1,opt,name=case_action1,json=caseAction1,proto3,enum=notification.CaseActionType_BalanceEnum,oneof"`
}

type CaseActionType_CaseAction2 struct {
	CaseAction2 CaseActionType_ApprovalEnum `protobuf:"varint,2,opt,name=case_action2,json=caseAction2,proto3,enum=notification.CaseActionType_ApprovalEnum,oneof"`
}

type CaseActionType_CaseAction3 struct {
	CaseAction3 CaseActionType_PlacementStatusEnum `protobuf:"varint,3,opt,name=case_action3,json=caseAction3,proto3,enum=notification.CaseActionType_PlacementStatusEnum,oneof"`
}

func (*CaseActionType_CaseAction1) isCaseActionType_CaseAction() {}

func (*CaseActionType_CaseAction2) isCaseActionType_CaseAction() {}

func (*CaseActionType_CaseAction3) isCaseActionType_CaseAction() {}

// =================
// Data
// =================
type NotificationData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LinkType string `protobuf:"bytes,3,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`
	Link     string `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *NotificationData) Reset() {
	*x = NotificationData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notification_proto_notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationData) ProtoMessage() {}

func (x *NotificationData) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationData.ProtoReflect.Descriptor instead.
func (*NotificationData) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationData) GetLinkType() string {
	if x != nil {
		return x.LinkType
	}
	return ""
}

func (x *NotificationData) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status    string            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Actor     string            `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	Data      *NotificationData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt string            `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReadAt    string            `protobuf:"bytes,6,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notification_proto_notification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_notification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_notification_proto_rawDescGZIP(), []int{2}
}

func (x *Notification) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Notification) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Notification) GetData() *NotificationData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Notification) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Notification) GetReadAt() string {
	if x != nil {
		return x.ReadAt
	}
	return ""
}

// =================
// Parameter Request
// =================
type GetNotificationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Page   uint32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit  uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetNotificationsRequest) Reset() {
	*x = GetNotificationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notification_proto_notification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsRequest) ProtoMessage() {}

func (x *GetNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_notification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetNotificationsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetNotificationsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UpdateReadStatusNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	String_ string `protobuf:"bytes,2,opt,name=string,proto3" json:"string,omitempty"`
}

func (x *UpdateReadStatusNotificationRequest) Reset() {
	*x = UpdateReadStatusNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notification_proto_notification_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReadStatusNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReadStatusNotificationRequest) ProtoMessage() {}

func (x *UpdateReadStatusNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_notification_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReadStatusNotificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateReadStatusNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_notification_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateReadStatusNotificationRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateReadStatusNotificationRequest) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionType     ActionTypeEnum  `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=notification.ActionTypeEnum" json:"action_type,omitempty"`
	CaseActionType *CaseActionType `protobuf:"bytes,2,opt,name=case_action_type,json=caseActionType,proto3" json:"case_action_type,omitempty"`
	IdTransaction  string          `protobuf:"bytes,3,opt,name=id_transaction,json=idTransaction,proto3" json:"id_transaction,omitempty"`
	Amount         uint64          `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notification_proto_notification_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_notification_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_notification_proto_rawDescGZIP(), []int{5}
}

func (x *SendNotificationRequest) GetActionType() ActionTypeEnum {
	if x != nil {
		return x.ActionType
	}
	return ActionTypeEnum_TOP_UP_BALANCE
}

func (x *SendNotificationRequest) GetCaseActionType() *CaseActionType {
	if x != nil {
		return x.CaseActionType
	}
	return nil
}

func (x *SendNotificationRequest) GetIdTransaction() string {
	if x != nil {
		return x.IdTransaction
	}
	return ""
}

func (x *SendNotificationRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// =================
// Response
// =================
type ListNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *Pagination     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Data       []*Notification `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListNotificationResponse) Reset() {
	*x = ListNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_notification_proto_notification_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationResponse) ProtoMessage() {}

func (x *ListNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notification_proto_notification_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_notification_proto_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ListNotificationResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListNotificationResponse) GetData() []*Notification {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_notification_proto_notification_proto protoreflect.FileDescriptor

var file_api_notification_proto_notification_proto_rawDesc = []byte{
	0x0a, 0x29, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe6, 0x04, 0x0a, 0x0e, 0x43, 0x61, 0x73, 0x65, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x63, 0x61, 0x73, 0x65, 0x5f,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x73,
	0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x61, 0x73, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x31, 0x12, 0x4e, 0x0a, 0x0c, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x73, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x61, 0x73, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x12, 0x55, 0x0a, 0x0c, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x30, 0x2e, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x73, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x48, 0x00,
	0x52, 0x0b, 0x63, 0x61, 0x73, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x33, 0x22, 0xa1, 0x01,
	0x0a, 0x0b, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x17, 0x0a,
	0x13, 0x77, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x10, 0x00, 0x12, 0x2a, 0x0a, 0x26, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x73, 0x73, 0x75, 0x65, 0x64, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x77, 0x61, 0x69,
	0x74, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x77, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x6f,
	0x72, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x02,
	0x12, 0x14, 0x0a, 0x10, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x65, 0x64, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x6f, 0x76, 0x65, 0x72, 0x64, 0x75, 0x65, 0x10,
	0x05, 0x22, 0x5b, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x45, 0x6e, 0x75,
	0x6d, 0x12, 0x1f, 0x0a, 0x1b, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x61, 0x6c, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73,
	0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x5f, 0x61, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x73, 0x5f, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x02, 0x22, 0x4e,
	0x0a, 0x13, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0d, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74,
	0x65, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x64, 0x10, 0x02,
	0x12, 0x0c, 0x0a, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x03, 0x42, 0x0d,
	0x0a, 0x0b, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x73, 0x0a,
	0x10, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69,
	0x6e, 0x6b, 0x22, 0xb8, 0x01, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x64, 0x41, 0x74, 0x22, 0x5b, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x4d, 0x0a, 0x23, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0xdf, 0x01, 0x0a, 0x17, 0x53, 0x65,
	0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x46, 0x0a, 0x10, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61,
	0x73, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e, 0x63, 0x61,
	0x73, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e,
	0x69, 0x64, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x7c, 0x0a, 0x18, 0x4c,
	0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0xa8, 0x01, 0x0a, 0x0e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x0e,
	0x54, 0x4f, 0x50, 0x5f, 0x55, 0x50, 0x5f, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x5f, 0x42, 0x41, 0x4c,
	0x41, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x43, 0x45, 0x49, 0x56,
	0x45, 0x44, 0x5f, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14,
	0x4c, 0x4f, 0x57, 0x5f, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x4d, 0x49,
	0x4e, 0x44, 0x45, 0x52, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56,
	0x41, 0x4c, 0x5f, 0x41, 0x50, 0x50, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x4d, 0x45, 0x4e,
	0x54, 0x10, 0x04, 0x12, 0x1f, 0x0a, 0x1b, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x41, 0x4c, 0x5f,
	0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x49, 0x5a, 0x45, 0x5f, 0x41, 0x50, 0x50, 0x5f, 0x50, 0x41,
	0x47, 0x45, 0x10, 0x05, 0x32, 0xb2, 0x02, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x25, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x67, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x31, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x32, 0x12, 0x4f, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x32, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_notification_proto_notification_proto_rawDescOnce sync.Once
	file_api_notification_proto_notification_proto_rawDescData = file_api_notification_proto_notification_proto_rawDesc
)

func file_api_notification_proto_notification_proto_rawDescGZIP() []byte {
	file_api_notification_proto_notification_proto_rawDescOnce.Do(func() {
		file_api_notification_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_notification_proto_notification_proto_rawDescData)
	})
	return file_api_notification_proto_notification_proto_rawDescData
}

var file_api_notification_proto_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_notification_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_notification_proto_notification_proto_goTypes = []interface{}{
	(ActionTypeEnum)(0),                         // 0: notification.ActionTypeEnum
	(CaseActionType_BalanceEnum)(0),             // 1: notification.CaseActionType.BalanceEnum
	(CaseActionType_ApprovalEnum)(0),            // 2: notification.CaseActionType.ApprovalEnum
	(CaseActionType_PlacementStatusEnum)(0),     // 3: notification.CaseActionType.PlacementStatusEnum
	(*CaseActionType)(nil),                      // 4: notification.CaseActionType
	(*NotificationData)(nil),                    // 5: notification.NotificationData
	(*Notification)(nil),                        // 6: notification.Notification
	(*GetNotificationsRequest)(nil),             // 7: notification.GetNotificationsRequest
	(*UpdateReadStatusNotificationRequest)(nil), // 8: notification.UpdateReadStatusNotificationRequest
	(*SendNotificationRequest)(nil),             // 9: notification.SendNotificationRequest
	(*ListNotificationResponse)(nil),            // 10: notification.ListNotificationResponse
	(*Pagination)(nil),                          // 11: meta.Pagination
	(*BaseResponseV2)(nil),                      // 12: meta.BaseResponseV2
}
var file_api_notification_proto_notification_proto_depIdxs = []int32{
	1,  // 0: notification.CaseActionType.case_action1:type_name -> notification.CaseActionType.BalanceEnum
	2,  // 1: notification.CaseActionType.case_action2:type_name -> notification.CaseActionType.ApprovalEnum
	3,  // 2: notification.CaseActionType.case_action3:type_name -> notification.CaseActionType.PlacementStatusEnum
	5,  // 3: notification.Notification.data:type_name -> notification.NotificationData
	0,  // 4: notification.SendNotificationRequest.action_type:type_name -> notification.ActionTypeEnum
	4,  // 5: notification.SendNotificationRequest.case_action_type:type_name -> notification.CaseActionType
	11, // 6: notification.ListNotificationResponse.pagination:type_name -> meta.Pagination
	6,  // 7: notification.ListNotificationResponse.data:type_name -> notification.Notification
	7,  // 8: notification.NotificationService.GetNotifications:input_type -> notification.GetNotificationsRequest
	8,  // 9: notification.NotificationService.UpdateReadStatusNotification:input_type -> notification.UpdateReadStatusNotificationRequest
	9,  // 10: notification.NotificationService.SendNotification:input_type -> notification.SendNotificationRequest
	10, // 11: notification.NotificationService.GetNotifications:output_type -> notification.ListNotificationResponse
	12, // 12: notification.NotificationService.UpdateReadStatusNotification:output_type -> meta.BaseResponseV2
	12, // 13: notification.NotificationService.SendNotification:output_type -> meta.BaseResponseV2
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_notification_proto_notification_proto_init() }
func file_api_notification_proto_notification_proto_init() {
	if File_api_notification_proto_notification_proto != nil {
		return
	}
	file_api_meta_proto_meta_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_notification_proto_notification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaseActionType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notification_proto_notification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotificationData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notification_proto_notification_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notification_proto_notification_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNotificationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notification_proto_notification_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReadStatusNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notification_proto_notification_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_notification_proto_notification_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_notification_proto_notification_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*CaseActionType_CaseAction1)(nil),
		(*CaseActionType_CaseAction2)(nil),
		(*CaseActionType_CaseAction3)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_notification_proto_notification_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notification_proto_notification_proto_goTypes,
		DependencyIndexes: file_api_notification_proto_notification_proto_depIdxs,
		EnumInfos:         file_api_notification_proto_notification_proto_enumTypes,
		MessageInfos:      file_api_notification_proto_notification_proto_msgTypes,
	}.Build()
	File_api_notification_proto_notification_proto = out.File
	file_api_notification_proto_notification_proto_rawDesc = nil
	file_api_notification_proto_notification_proto_goTypes = nil
	file_api_notification_proto_notification_proto_depIdxs = nil
}
