// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/placement-service.proto

package documents

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PlacementService_ServeRevokePlacementDocument_FullMethodName      = "/placementpb.PlacementService/ServeRevokePlacementDocument"
	PlacementService_ServeListRevokedPlacementDocument_FullMethodName = "/placementpb.PlacementService/ServeListRevokedPlacementDocument"
	PlacementService_ServeUpdatePlacementDocument_FullMethodName      = "/placementpb.PlacementService/ServeUpdatePlacementDocument"
)

// PlacementServiceClient is the client API for PlacementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlacementServiceClient interface {
	ServeRevokePlacementDocument(ctx context.Context, in *RevokePlacementDocumentRequest, opts ...grpc.CallOption) (*PlacementDocumentResponse, error)
	ServeListRevokedPlacementDocument(ctx context.Context, in *PlacementDocParameterRequest, opts ...grpc.CallOption) (*ListPlacementDocumentResponse, error)
	ServeUpdatePlacementDocument(ctx context.Context, in *UpdatePlacementDocumentRequest, opts ...grpc.CallOption) (*PlacementDocumentResponse, error)
}

type placementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlacementServiceClient(cc grpc.ClientConnInterface) PlacementServiceClient {
	return &placementServiceClient{cc}
}

func (c *placementServiceClient) ServeRevokePlacementDocument(ctx context.Context, in *RevokePlacementDocumentRequest, opts ...grpc.CallOption) (*PlacementDocumentResponse, error) {
	out := new(PlacementDocumentResponse)
	err := c.cc.Invoke(ctx, PlacementService_ServeRevokePlacementDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placementServiceClient) ServeListRevokedPlacementDocument(ctx context.Context, in *PlacementDocParameterRequest, opts ...grpc.CallOption) (*ListPlacementDocumentResponse, error) {
	out := new(ListPlacementDocumentResponse)
	err := c.cc.Invoke(ctx, PlacementService_ServeListRevokedPlacementDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placementServiceClient) ServeUpdatePlacementDocument(ctx context.Context, in *UpdatePlacementDocumentRequest, opts ...grpc.CallOption) (*PlacementDocumentResponse, error) {
	out := new(PlacementDocumentResponse)
	err := c.cc.Invoke(ctx, PlacementService_ServeUpdatePlacementDocument_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlacementServiceServer is the server API for PlacementService service.
// All implementations must embed UnimplementedPlacementServiceServer
// for forward compatibility
type PlacementServiceServer interface {
	ServeRevokePlacementDocument(context.Context, *RevokePlacementDocumentRequest) (*PlacementDocumentResponse, error)
	ServeListRevokedPlacementDocument(context.Context, *PlacementDocParameterRequest) (*ListPlacementDocumentResponse, error)
	ServeUpdatePlacementDocument(context.Context, *UpdatePlacementDocumentRequest) (*PlacementDocumentResponse, error)
	mustEmbedUnimplementedPlacementServiceServer()
}

// UnimplementedPlacementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlacementServiceServer struct {
}

func (UnimplementedPlacementServiceServer) ServeRevokePlacementDocument(context.Context, *RevokePlacementDocumentRequest) (*PlacementDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServeRevokePlacementDocument not implemented")
}
func (UnimplementedPlacementServiceServer) ServeListRevokedPlacementDocument(context.Context, *PlacementDocParameterRequest) (*ListPlacementDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServeListRevokedPlacementDocument not implemented")
}
func (UnimplementedPlacementServiceServer) ServeUpdatePlacementDocument(context.Context, *UpdatePlacementDocumentRequest) (*PlacementDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServeUpdatePlacementDocument not implemented")
}
func (UnimplementedPlacementServiceServer) mustEmbedUnimplementedPlacementServiceServer() {}

// UnsafePlacementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlacementServiceServer will
// result in compilation errors.
type UnsafePlacementServiceServer interface {
	mustEmbedUnimplementedPlacementServiceServer()
}

func RegisterPlacementServiceServer(s grpc.ServiceRegistrar, srv PlacementServiceServer) {
	s.RegisterService(&PlacementService_ServiceDesc, srv)
}

func _PlacementService_ServeRevokePlacementDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokePlacementDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementServiceServer).ServeRevokePlacementDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementService_ServeRevokePlacementDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementServiceServer).ServeRevokePlacementDocument(ctx, req.(*RevokePlacementDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacementService_ServeListRevokedPlacementDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlacementDocParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementServiceServer).ServeListRevokedPlacementDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementService_ServeListRevokedPlacementDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementServiceServer).ServeListRevokedPlacementDocument(ctx, req.(*PlacementDocParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacementService_ServeUpdatePlacementDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlacementDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacementServiceServer).ServeUpdatePlacementDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacementService_ServeUpdatePlacementDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacementServiceServer).ServeUpdatePlacementDocument(ctx, req.(*UpdatePlacementDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlacementService_ServiceDesc is the grpc.ServiceDesc for PlacementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlacementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "placementpb.PlacementService",
	HandlerType: (*PlacementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServeRevokePlacementDocument",
			Handler:    _PlacementService_ServeRevokePlacementDocument_Handler,
		},
		{
			MethodName: "ServeListRevokedPlacementDocument",
			Handler:    _PlacementService_ServeListRevokedPlacementDocument_Handler,
		},
		{
			MethodName: "ServeUpdatePlacementDocument",
			Handler:    _PlacementService_ServeUpdatePlacementDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/placement-service.proto",
}
